Add decisions and revisions for physicalDescription from 8-4-2020 mee…
UTKcataloging/mods_to_rdf pull request #16
Opened 2020-08-07 18:55 UTC by mlhale7

## What does this Pull Request do?

This PR adds decisions made verbally in our 8-4 and 8-7 meetings about the top-level element physicalDescription.

## What's new?

Use cases, Xpaths, justifications, and decisions were added for the following:
mods:physicalDescription/mods:note
mods:physicalDescription/mods:extent
mods:physicalDescription/mods:extent[@unit="pages"]
mods:physicalDescription/mods:form[@type="material"]

## How should this be tested?

Are any of the justifications not articulated properly or is the rst not formatted correctly?

## Interested parties

@markpbaggett @CanOfBees @mathewjordan

2020-08-18 17:06 UTC, markpbaggett reviewed
@mlhale7, thanks for putting this together. I think that rdau adds some complexities that we need to revisit and perhaps document in our philosophy.

When we discussed rdau, we decided that although it did not adhere to best practices for RDF and content negotiation in general that we would make an exception because it was important to separate extent into its own rdf property. To do this, we selected this rdf property:  `http://rdaregistry.info/Elements/u/#extent.en`. A few things about this property that I've noticed:

1. Even though rdau is not content negotiable, they include the RDF as a downloadable attachment. The actual rdf property listed here is <http://rdaregistry.info/Elements/u/P60550>.  We took the other URI from the Samvera working doc, which in my opinion is wrong. <http://rdaregistry.info/Elements/u/P60550> has a <http://metadataregistry.org/uri/profile/regap/lexicalAlias> with the value of <http://rdaregistry.info/Elements/u/extent.en>.
2. You'll notice that even the object of <http://metadataregistry.org/uri/profile/regap/lexicalAlias> doesn't match our examples.

I'm still okay with using rdau if others think we should, but I don't think we've chosen the right property and should reevaluate.  If we decide to use this property, I think we should justify it.

2020-08-18 17:06 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +rdau:extent
I think this property was copied and pasted here accidentally.

2020-08-18 17:06 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +        rdau:extent.en "3 1/4 x 5 inches" .
See the message in my review.  Also, the turtle lexer does not like namespaced URIs like this. If we don't change properties, I think we should just use the full URI.

2020-08-18 17:06 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +        rdau:extent.en "4 pages" .
See the message in my review. Also, the turtle lexer does not like namespaced URIs like this. If we don't change properties, I think we should just use the full URI.

2020-08-18 17:14 UTC, markpbaggett commented
One more note:

rdau states:

``All RDA URIs have both an immutable canonical form and a "readable", lexical form, which is subject to change (changes will be redirected).```

This is not true, and our example is proof of that.

2020-08-19 19:33 UTC, mlhale7 commented
@markpbaggett - I believe I addressed your comments with the newest commit. Let me know if I've misunderstood.

2020-08-20 13:07 UTC, markpbaggett requested changes

2020-08-20 13:07 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +    @prefix rdau: <http://rdaregistry.info/Elements/u/#> .
Change the URI to : <http://rdaregistry.info/Elements/u/>

2020-08-20 13:07 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +        http://rdaregistry.info/Elements/u/P60550 "3 1/4 x 5 inches" .
@mlhale7, the lexer didn't like the "." in the namespaced uri.  Can you change this to:

```
rdau:P60550
```
or

```
<http://rdaregistry.info/Elements/u/P60550>
```

2020-08-20 13:07 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +        rdau:extent.en "4 pages" .
@mlhale7, the lexer didn't like the "." in the namespaced uri.  Can you change this to:

```
rdau:P60550
```
or

```
<http://rdaregistry.info/Elements/u/P60550>
```

2020-08-20 13:07 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +    @prefix rdau: <http://rdaregistry.info/Elements/u/#> .
Change this to:

```
@prefix rdau: <http://rdaregistry.info/Elements/u/> .
```

2020-08-20 15:56 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +        http://rdaregistry.info/Elements/u/P60550 "3 1/4 x 5 inches" .
Thanks - I didn't realize I completely left off the carrots. I think the other option is cleaner though and will commit that.

2020-08-20 15:57 UTC, mlhale7 commented
@markpbaggett - thanks for clearing up my misunderstandings. I've committed your suggestions.

2020-08-21 13:18 UTC, markpbaggett requested changes
> @markpbaggett - thanks for clearing up my misunderstandings. I've committed your suggestions.

Meredith, we still have a problem:

1. 253 - 256 looks like this:

```
.. code-block:: turtle

    @prefix rdau: <http://rdaregistry.info/Elements/u/#> .

    <https://example.org/objects/1>
        rdau:extent.en "4 pages" .
```

but it should look like this:

```
.. code-block:: turtle

    @prefix rdau: <http://rdaregistry.info/Elements/u/> .

    <https://example.org/objects/1>
        rdau:P60550  "4 pages" .
```

2020-08-21 13:19 UTC, markpbaggett commented on docs/source/contents/4_draft_mapping.rst
> +        rdau:extent.en "4 pages" .
This is still an issue.  See below.

2020-08-21 13:33 UTC, mlhale7 commented
@markpbaggett - apologies for completely overlooking that the same issue needed to be changed twice. Hopefully I've addressed everything now.

2020-08-21 16:25 UTC, markpbaggett approved these changes

2020-08-21 16:25 UTC, merged