originInfo mapping
UTKcataloging/mods_to_rdf pull request #39
Opened 2020-10-30 17:37 UTC by CanOfBees

**JIRA Issue**: `DIGITAL-754 <https://jirautk.atlassian.net/browse/DIGITAL-754>`_

What Does this Do?
==================
This builds upon the originInfo analysis and provides final decisions to mapping document.

How Should This Be Tested?
==========================
Do tests pass? (probably not!...)
Are the contents consistent and properties justifiable?
Are slepping orrers verywhere?

Additional Notes
================
Things should hopefully be faithful to the analysis document.

2020-10-30 19:02 UTC, mlhale7 requested changes
Final question - didn't we have copyrightDate ([calahan:1](https://digital.lib.utk.edu/collections/islandora/object/calahan%3A1)) and maybe even dateCaptured in the initial analysis doc?

2020-10-30 19:02 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +`kintner:56 <https://digital.lib.utk.edu/collections/islandora/object/kintner%3A56>`_
This entire collection (kintner) was remediated this summer, so the example is no longer relevant. Can you select another instance of dateOther (assuming there are still several hanging out) from another collection? As a group, we should talk more about what are expectations are for our mapping matching our present metadata since the metadata is always changing.

2020-10-30 19:02 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +        <place supplied="yes">
It looks like we are disregarding the supplied attribute (which I am fine with). Can we specify that we are making this decision?

2020-10-30 19:02 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +:code:`originInfo/publisher`
I didn't notice this until this Xpath, but you are using a less verbose Xpath throughout. @markpbaggett and @mathewjordan, for consistency do we always want to include "mods" - aka mods:originInfo/mods:publisher?

2020-10-30 19:02 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +We will not be migrating `issuance`.
We might want to elaborate a little on why here - it isn't consistently applied, we don't currently display this value publicly, etc.

2020-10-30 19:02 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +We will not be migrating `issuance`.
I'd also include all the sections - Use Case, Justification, Xpath, Decision.

2020-11-03 16:25 UTC, CanOfBees commented on docs/source/contents/4_draft_mapping.rst
> +`kintner:56 <https://digital.lib.utk.edu/collections/islandora/object/kintner%3A56>`_
@mlhale7 thanks for catching this - I've updated w/a playbills example.

2020-11-03 16:26 UTC, CanOfBees commented on docs/source/contents/4_draft_mapping.rst
> +:code:`originInfo/publisher`
@mlhale7 - I think I should follow suit and add the namespace prefix.

2020-11-03 16:34 UTC, CanOfBees commented on docs/source/contents/4_draft_mapping.rst
> +        <place supplied="yes">
@mlhale7 can you clarify? Would you prefer `` :code:`originInfo/place[\@supplied='yes']/placeTerm[\@text][\@valueURI]` `` in the XPath section? Or am I completely missing your point? 

Thanks!

2020-11-03 19:27 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +        <place supplied="yes">
I was wondering if we wanted to acknowledge the loss of this information in the document (though as I said, I don't think much is lost). No Xpath changes are necessary. I'm happy to approve with this, it just wasn't something we discussed.

2020-11-03 19:27 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +:code:`originInfo/publisher`
As we discussed in our meeting, we'll deal with consistency in the final editing. A strong argument was made for being less verbose.

2020-11-03 19:29 UTC, mlhale7 commented on docs/source/contents/4_draft_mapping.rst
> +We will not be migrating `issuance`.
@CanOfBees - thanks for the additions.

2020-11-03 19:29 UTC, mlhale7 approved these changes

2020-11-03 19:51 UTC, markpbaggett approved these changes
Sounds good.

2020-11-03 19:52 UTC, merged