Add Egypt name to working docs
UTKcataloging/mods_to_rdf pull request #6
Opened 2020-07-10 14:44 UTC by mathewjordan

This is work collaborated on between the brains of @CanOfBees and @mathewjordan. It's an attempt for us to evaluate the three recommendations (1 Islandora, 2 Samvera) in a focused way on a single element. In this example we focused on **<name>**. 

Note that the `<namePart type="date">19th-20th centuries</namePart>` is not translated to any of the RDF examples. Could have done this in some way?

This won't appear in the updated docs until merged.

https://digital.lib.utk.edu/collections/islandora/object/egypt%3A101/datastream/MODS/view

@mlhale7 @markpbaggett @CanOfBees

2020-07-10 16:55 UTC, markpbaggett requested changes

2020-07-10 16:55 UTC, markpbaggett commented on docs/source/working_docs/egypt_name.rst
> +        schema:sameAs <ulan:500057278> ;
Samvera does not use schema:sameAs.  They use owl:sameAs. See page 69.

2020-07-21 17:51 UTC, mathewjordan commented
@markpbaggett made the requested changes. 

```
@prefix relators: <http://id.loc.gov/vocabulary/relators> .
    @prefix ulan: <http://vocab.getty.edu/ulan> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix foaf: <http://xmlns.com/foaf/spec/> .

    <https://example.org/objects/1> relators:pht <https://example.org/name/1> .

    <https://example.org/name/1> a foaf:Organization ;
        owl:sameAs <ulan:500057278> ;
        foaf:name "Bonfils Family"@en .
```

2020-07-21 19:17 UTC, markpbaggett approved these changes

2020-07-21 19:17 UTC, merged